name: React Tests

on: [push]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - name: Modules
      run: |
        npm i --save
    - name: Tests
      env:
        CI: true
      run: |
        npm test --watchAll=false --passWithNoTests
    - name: Build
      env:
        CI: true
      run: |
        npm run build
